### ISSUE TITLE
Ajustes el modelo de datos de descuentos matrículas

### ISSUE THREAD

**Issue by mafeave** [udistrital/descuento_academico_crud#1]
De acuerdo a reunión realizada, se debe tener en cuenta que un descuento está asociado no necesariamente al concepto de matrícula, puede a futuro aplicar a cualquier derecho pecuniario.

**Comment by mafeave** [comment]
Se parte de lo definido en el [Acuerdo 004 de 2006](https://sgral.udistrital.edu.co/xdata/csu/acu_2006-004.pdf) y [Acuerdo 010 de 2006](https://sgral.udistrital.edu.co/xdata/ca/acu_2006-010.pdf), Estatutos Relacionados con la Liquidación de Matrículas e Incentivos.

- Se agrega tabla paramétrica para los conceptos por lo cuales podría haber descuentos: derechos pecuniarios y matrícula
- Se agrega tabla para almacenar los documentos que se anexan a la solicitud de descuento
- Se agrega la tabla tipo_duracion, para saber la periodicidad en la cual el descuento se va a seguir manteniendo
- Se agregan tablas para gestionar los requisitos por tipo de descuento, evaluar si a futuro sería mejor dejarlo plasmado en el ruler

La imagen y el modelo se encuentran en: https://drive.google.com/drive/u/0/folders/1MUiMJKbPqc-6kQg-WFkVIYEwBZZAWdLs

**Comment by mafeave** [comment]
Está pendiente reunión con DBA y Arquitecto para validar el modelo

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 17 de julio, se expone la versión 11 del modelo de datos de descuentos academicos. Se corriguen los nombres de los campo donde se refencian a otros esquemas agregando el subfijo _id, adicionalmente se acada la sugerencia de agregar notas para aclarar a que esquema y sistema referencian esos campos, la tabla conceptos se mueve para el esquema de core y se crea el campo valor_con_descuento en la tabla validacion_descuento para poder realizar el calculo del valor de descuento realizado. Se expone la siguiente figura del modelo de datos con las correciones correspondientes.

![descuentos_academicos](https://user-images.githubusercontent.com/43799065/61467672-a05e1700-a941-11e9-9157-a3ac54d543e1.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm de modelo propuesto.
[descuentos.dbm.zip](https://github.com/udistrital/matricula_descuentos_crud/files/3407085/descuentos.dbm.zip)

**Comment by mafeave** [comment]
Modelo anexado en el kanban de revisión con el arquitecto y DBA, ver[ kanban N° 31216](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=31216)
