### ISSUE TITLE
Ajustar el Api de descuento_academico_crud 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/descuento_academico_crud#2]
Ajuste del CRUD para el modelo de datos del esquema descuentos academicos establecido en el [modelo](https://drive.google.com/drive/folders/1oHPdamuQ1XukHKz34DrqVioziOlUe9hF), el API debe cumplir con los siguientes requerimientos:

- [x] El crud debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El crud debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se agrega los modelos, controladores y rutas necesaria para ajustar el api descuentos_academico_crud con el modelo establecido nuevo, necesaria para el modelo de datos de descuentos.

**Comment by fabianbarreto02** [comment]
El modelo de datos con el que se trabajo el api se expone en la siguien imagen.

![descuento_matriculaV2](https://user-images.githubusercontent.com/43799065/61495320-4e87b200-a97e-11e9-8575-74995a7bca63.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm.
[descuento_matriculaV2.dbm.zip](https://github.com/udistrital/descuento_academico_crud/files/3408606/descuento_matriculaV2.dbm.zip)

**Comment by fabianbarreto02** [comment]
El api ajustado se encuentra desarrollada en la rama Version11 del [repositorio](https://github.com/udistrital/descuento_academico_crud/tree/Version11) descuento_academico_crud, se espera la revisión por parte de la lider técnica: @mafeave .

**Comment by mafeave** [comment]
Se revisan los ajustes realizados en el API, ajustar lo siguiente:
- la dirección de los modelos en los controladores, la dirección debe contener el nombre del repositorio: "github.com/udistrital/descuento_academico_crud/models"
- eliminar el archivo main_test.go

**Comment by fabianbarreto02** [comment]
Se realizan las correciones realizadar por parte de la lider técnica.

**Comment by mafeave** [comment]
Se revisan los ajustes solicitados, se da por finalizada la tarea.
